name: Deployment - reusable workflow

on:

  workflow_call:
    inputs:
      mongo-uri:
        type: string
        required: true

      kubectl-version:
        type: string
        required: false
        description: kubectl version
        default: v1.26.0

      deployment-path:
        type: string
        required: true
        default: 'kubernetes/development/'

    secrets:
        mongodb-secret:
            required: true
    outputs:
      app-url:
        value: ${{ jobs.reusable-job.outputs.APP_INGRESS_URL }}

jobs:
    reusable-job:
      outputs:
        APP_INGRESS_URL: ${{ steps.APP_INGRESS_HOST.outputs.APP_INGRESS_HOST }}

      runs-on: ubuntu-latest
      steps:
        - name: Checkout the repo
          uses: actions/checkout@v6

        - name: Setup kubectl
          uses: azure/setup-kubectl@v4
          with:
            version: '${{ inputs.kubectl-version }}' # default is latest stable


        
        - name: Setup and start minikube
          id: minikube
          uses: medyagh/setup-minikube@latest

        - name: Setup addons and Fetch kubernetes cluster details
          run: |
            echo "Setup ingress on minikube"
            minikube addons enable ingress

            minikube tunnel &

            echo ---------------------------------
            kubectl get nodes
            echo ---------------------------------
            kubectl get pods -n ingress-nginx

            echo "Get ingress IP"
            kubectl get services ingress-nginx-controller -n ingress-nginx  -o jsonpath="{.status.loadBalancer.ingress[0].ip}"

            echo "get yrl from minikube service "
            minikube service ingress-nginx-controller -n ingress-nginx --url


       
        - name: SET GITHUB ENVIRONMENT VARIABLES
          run: |
            echo "NAME=hello" >> $GITHUB_ENV
            echo "INGRESS_IP=$(minikube ip)" >> $GITHUB_ENV

        - name: Replace Token in files
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '${'
            tokenSuffix: '}'
            files: '["${{ inputs.deployment-path }}*.yaml"]'
          env:
            NAMESPACE: ${{ vars.NAMESPACE }}
            NAME: ${{ env.NAME }}
            INGRESS_IP: ${{ env.INGRESS_IP }}

        - name: Check files
          run: cat ${{ inputs.deployment-path }}*.yaml

        - name: Create MongoDB screts
          run: |
           kubectl create namespace ${{ vars.NAMESPACE }}
           kubectl  -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
           --from-literal=MONGO_URI=${{ inputs.mongo-uri }} \
           --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
           --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-secret }} \
           --save-config \
           --dry-run=client \
           -o yaml | kubectl apply -f -

        - name: Deploy the app
          run: |
           echo "deployed"
           kubectl apply -f ${{ inputs.deployment-path }} -n ${{ vars.NAMESPACE }}

        - name: Set APP INGRESS HOT URL
          id: APP_INGRESS_HOST
          run: |
            echo "APP_INGRESS_HOST=$(minikube ip)" >> $GITHUB_OUTPUT