name: Solar System Workflow

on:
    workflow_dispatch: 
    push:
        branches:
            - main
            - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
              node-version: [18, 19, 20]
              os: [ubuntu-latest, windows-latest]
              exclude:
                - node-version: 18
                  os: windows-latest

        runs-on: ${{ matrix.os }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6

        - name: Setup NodeJS Version -${{ matrix.node-version }}
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install Depedencies
          run: npm install

        - name: Unit Testing
          id: unit-test
          run: npm test

        - uses: actions/upload-artifact@v6
          name: Upload Artifacts
          if: failure() && (steps.unit-test.outcome == 'failure' || steps.unit-test.outcome == 'success')
          with:
            name: Mocha-Test-Artifacts-${{ matrix.os }}-node-${{ matrix.node-version }}
            path: test-results.xml
    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6

        - name: Setup NodeJS Version - 18
          uses: actions/setup-node@v6
          with:
            node-version: 18

        - name: Install Depedencies
          run: npm install

        - name: Code Coverage
          continue-on-error: true
          run: npm run coverage

        - uses: actions/upload-artifact@v6
          name: Upload Artifacts
          with:
            name: Code-Coverage
            path: coverage
            retention-days: 5

